### ISSUE TITLE
Docs on environment variables

### ISSUE THREAD

**Issue by progsmile** [NoEnv/docker-openldap#1]
Hello dear maintainers!
Where can I find description what environment variables should be used?
Thanks.

**Comment by zyclonite** [comment]
there aren't any... the idea is to mount the configuration and data directory into the container without doing any magic on the entrypoint script

example run command would be something like: `docker run -d -p 389:389 -v /opt/ldap/conf:/etc/ldap -v /opt/ldap/db:/var/lib/ldap noenv/openldap`

**Comment by progsmile** [comment]
Ok, I've got it. Thanks!
